### ISSUE TITLE
system-config-printer works not

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2743]
**OpenMandriva version**: 
Cooker and Cooker ISO 'Live'

**Describe the bug**: 
system-config-printer does not open

**Steps to reproduce**:
In fully distro-synced cooker system or Cooker ISO 'Live' Try to open system-config-printer

**Observed behavior**: 
s-c-p does  not open

**Expected behavior**: 
s-c-p should open and allow user to set up and manage printer

**Additional comment**: Not sure is this is a blocker for OM Lx 4.3. We do have other options for configuring printers: kcm_printer_manager and CUPS.

**Logs and screenshots if relevant**
Konsole ouput:
```
$ system-config-printer

(system-config-printer.py:2132): dbind-WARNING **: 19:01:39.443: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Traceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 2264, in <module>
    main(show_jobs)
  File "/usr/share/system-config-printer/system-config-printer.py", line 2234, in main
    mainwindow = GUI()
  File "/usr/share/system-config-printer/system-config-printer.py", line 274, in __init__
    printer_manager_action_group.add_actions ([
AttributeError: 'ActionGroup' object has no attribute 'add_actions'

```
OMDV Bug Report Log:
[omdv-bug-report-20211003191440.log](https://github.com/OpenMandrivaAssociation/distribution/files/7274771/omdv-bug-report-20211003191440.log)

**Comment by AngryPenguinPL** [comment]
still works for me... which makes it quite strange. Tomorrow I will try to check live iso.
![Zrzut ekranu z 2021-10-04 02-27-13](https://user-images.githubusercontent.com/3121142/135778910-42456ec4-4fcb-4caf-8fcf-dbfd0df045f7.png)

**Comment by benbullard79** [comment]
I am checking on more than one system plus our ISO's. No at-spi package installed on any.

**Comment by benbullard79** [comment]
We don't seem to have at-spi anymore. Only at-spi2-atk and associates and at-spi2-core and it's associates.

**Comment by benbullard79** [comment]
But I missed that these are installed:
```
# rpm -qa | grep lib64atspi
lib64atspi0-2.42.0-1.x86_64

# rpm -qa | grep lib64atk
lib64atk1.0_0-2.36.0-5.x86_64
lib64atk-bridge2.0_0-2.38.0-3.x86_64
lib64atk-gir1.0-2.36.0-5.x86_64
```
It would look like those might be the packages needed to get s-c-p to work.

I tried installing at-spi2-atk and at-spi2-core and that did not help.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/new-cooker-om-lx-4-3-preview-isos/4222/5

**Comment by AngryPenguinPL** [comment]
I am 100% sure that this is the missing dependency.
That's why it works on two PCs from the existing Cooker installation, but it does not work on a fresh live ISO.
Today on Live ISO I started installing packages in groups from GTK family packages like atk *, glib *, cairo *, pango * etc and after some package groups the application started working.

Now we need to determine exactly which package is needed and add it on ISO or as requires to system-config-printer.

Here is a list of installed by me packages:

```
python-libsignon-glib-2.1-6.x86_64            Tue 05 Oct 2021 02:59:22 PM BST
python-libgit2-glib-0.99.0.1-3.noarch         Tue 05 Oct 2021 02:59:22 PM BST
python-gobject3-3.42.0-1.x86_64               Tue 05 Oct 2021 02:59:22 PM BST
lib64upower-glib-gir1.0-0.99.13-1.x86_64      Tue 05 Oct 2021 02:59:22 PM BST
lib64taglib_c0-1.11.1-9.x86_64                Tue 05 Oct 2021 02:59:22 PM BST
lib64spice-client-glib-gir2.0-0.39-1.x86_64   Tue 05 Oct 2021 02:59:22 PM BST
lib64spice-client-glib2.0_8-0.39-1.x86_64     Tue 05 Oct 2021 02:59:22 PM BST
lib64signon-glib-gir1.0-2.1-6.x86_64          Tue 05 Oct 2021 02:59:22 PM BST
lib64pyglib2.0_0-2.28.7-1.x86_64              Tue 05 Oct 2021 02:59:22 PM BST
lib64jsonrpc_glib1.0_1-3.40.0-1.x86_64        Tue 05 Oct 2021 02:59:22 PM BST
lib64gtk-gir4.0-4.4.0-1.x86_64                Tue 05 Oct 2021 02:59:22 PM BST
lib64git2-glib1.0_0-0.99.0.1-3.x86_64         Tue 05 Oct 2021 02:59:22 PM BST
lib64geocode-glib-gir1.0-3.26.2-4.x86_64      Tue 05 Oct 2021 02:59:22 PM BST
lib64geocode-glib0-3.26.2-4.x86_64            Tue 05 Oct 2021 02:59:22 PM BST
lib64dbusmenu-glib4-16.04.0-4.x86_64          Tue 05 Oct 2021 02:59:22 PM BST
lib64dbusglib-gir1.0-1.70.0-1.x86_64          Tue 05 Oct 2021 02:59:22 PM BST
lib64cacard0-2.7.0-1.x86_64                   Tue 05 Oct 2021 02:59:22 PM BST
json-glib-1.6.6-2.x86_64                      Tue 05 Oct 2021 02:59:22 PM BST
gtk4.0-4.4.0-1.x86_64                         Tue 05 Oct 2021 02:59:22 PM BST
geocode-glib-3.26.2-4.x86_64                  Tue 05 Oct 2021 02:59:22 PM BST
phodav-i18n-2.5-3.noarch                      Tue 05 Oct 2021 02:59:21 PM BST
lib64usbredirparser1-0.8.0-3.x86_64           Tue 05 Oct 2021 02:59:21 PM BST
lib64usbredirhost1-0.8.0-3.x86_64             Tue 05 Oct 2021 02:59:21 PM BST
lib64soup-gir2.4-2.74.0-2.x86_64              Tue 05 Oct 2021 02:59:21 PM BST
lib64python2.7_1-2.7.18-1.x86_64              Tue 05 Oct 2021 02:59:21 PM BST
lib64phodav2.0_0-2.5-3.x86_64                 Tue 05 Oct 2021 02:59:21 PM BST
lib64json-glib-gir1.0-1.6.6-2.x86_64          Tue 05 Oct 2021 02:59:21 PM BST
lib64gtk4_1-4.4.0-1.x86_64                    Tue 05 Oct 2021 02:59:21 PM BST
lib64gstplayer1.0_0-1.18.4-4.x86_64           Tue 05 Oct 2021 02:59:21 PM BST
lib64gst-gir1.0-1.19.1-1.x86_64               Tue 05 Oct 2021 02:59:21 PM BST
lib64gstcheck1.0_0-1.19.1-1.x86_64            Tue 05 Oct 2021 02:59:21 PM BST
lib64graphene-gir1.0-1.10.2-1.x86_64          Tue 05 Oct 2021 02:59:21 PM BST
lib64colord2-1.4.5-3.x86_64                   Tue 05 Oct 2021 02:59:21 PM BST
lib64pangoot-gir1.0-1.48.10-1.x86_64          Tue 05 Oct 2021 02:56:50 PM BST
lib64pangomm2.48_1-2.48.1-2.x86_64            Tue 05 Oct 2021 02:56:50 PM BST
lib64pangomm1.4_1-2.46.1-2.x86_64             Tue 05 Oct 2021 02:56:50 PM BST
lib64pangofc-gir1.0-1.48.10-1.x86_64          Tue 05 Oct 2021 02:56:50 PM BST
lib64gl-gir1.0-1.70.0-1.x86_64                Tue 05 Oct 2021 02:56:50 PM BST
lib64giomm2.68_1-2.68.1-2.x86_64              Tue 05 Oct 2021 02:56:50 PM BST
lib64freetype-gir2.0-1.70.0-1.x86_64          Tue 05 Oct 2021 02:56:50 PM BST
lib64fontconfig-gir2.0-1.70.0-1.x86_64        Tue 05 Oct 2021 02:56:50 PM BST
lib64cogl-pango-gir2.0-1.22.8-4.x86_64        Tue 05 Oct 2021 02:56:50 PM BST
lib64cogl-pango-gir1.0-1.22.8-4.x86_64        Tue 05 Oct 2021 02:56:50 PM BST
lib64cogl-pango20-1.22.8-4.x86_64             Tue 05 Oct 2021 02:56:50 PM BST
lib64cogl-gir2.0-1.22.8-4.x86_64              Tue 05 Oct 2021 02:56:50 PM BST
lib64cogl-gir1.0-1.22.8-4.x86_64              Tue 05 Oct 2021 02:56:50 PM BST
lib64cogl20-1.22.8-4.x86_64                   Tue 05 Oct 2021 02:56:50 PM BST
lib64pangocairo-gir1.0-1.48.10-1.x86_64       Tue 05 Oct 2021 02:55:18 PM BST
lib64cairomm1.16_1-1.16.1-2.x86_64            Tue 05 Oct 2021 02:55:18 PM BST
lib64cairomm1.0_1-1.12.2-6.x86_64             Tue 05 Oct 2021 02:55:18 PM BST
lib64sigc++3.0_0-3.0.7-2.x86_64               Tue 05 Oct 2021 02:54:01 PM BST
lib64glibmm2.68_1-2.68.1-2.x86_64             Tue 05 Oct 2021 02:54:01 PM BST
lib64atkmm2.36_1-2.36.1-2.x86_64              Tue 05 Oct 2021 02:54:01 PM BST
lib64atkmm1.6_1-2.28.2-2.x86_64               Tue 05 Oct 2021 02:54:01 PM BST
x11-proto-devel-2021.5-1.noarch               Tue 05 Oct 2021 02:53:16 PM BST
lib64z-devel-2.0.5-2.x86_64                   Tue 05 Oct 2021 02:53:16 PM BST
lib64xtst-devel-1.2.3-5.x86_64                Tue 05 Oct 2021 02:53:16 PM BST
lib64xt-devel-1.2.1-1.x86_64                  Tue 05 Oct 2021 02:53:16 PM BST
lib64xi-devel-1.8-1.x86_64                    Tue 05 Oct 2021 02:53:16 PM BST
lib64xfixes-devel-6.0.0-1.x86_64              Tue 05 Oct 2021 02:53:16 PM BST
lib64xext-devel-1.3.4-2.x86_64                Tue 05 Oct 2021 02:53:16 PM BST
lib64uuid-devel-2.37.2-1.x86_64               Tue 05 Oct 2021 02:53:16 PM BST
lib64pcreposix1-8.45-1.x86_64                 Tue 05 Oct 2021 02:53:16 PM BST
lib64pcreposix0-8.45-1.x86_64                 Tue 05 Oct 2021 02:53:16 PM BST
lib64pcre-devel-8.45-1.x86_64                 Tue 05 Oct 2021 02:53:16 PM BST
lib64pcrecpp0-8.45-1.x86_64                   Tue 05 Oct 2021 02:53:16 PM BST
lib64pcre32_0-8.45-1.x86_64                   Tue 05 Oct 2021 02:53:16 PM BST
lib64pcre16_0-8.45-1.x86_64                   Tue 05 Oct 2021 02:53:16 PM BST
lib64mount-devel-2.37.2-1.x86_64              Tue 05 Oct 2021 02:53:16 PM BST
lib64ice-devel-1.0.10-2.x86_64                Tue 05 Oct 2021 02:53:16 PM BST
lib64glib2.0-devel-2.70.0-1.x86_64            Tue 05 Oct 2021 02:53:16 PM BST
lib64ffi-devel-3.3-3.x86_64                   Tue 05 Oct 2021 02:53:16 PM BST
lib64dbus-gir1.0-1.70.0-1.x86_64              Tue 05 Oct 2021 02:53:16 PM BST
lib64cryptsetup-devel-2.3.6-1.x86_64          Tue 05 Oct 2021 02:53:16 PM BST
lib64blkid-devel-2.37.2-1.x86_64              Tue 05 Oct 2021 02:53:16 PM BST
lib64atspi-gir2.0-2.42.0-1.x86_64             Tue 05 Oct 2021 02:53:16 PM BST
lib64atspi-devel-2.42.0-1.x86_64              Tue 05 Oct 2021 02:53:16 PM BST
lib64atk-bridge-devel-2.38.0-3.x86_64         Tue 05 Oct 2021 02:53:16 PM BST
lib64atk1.0-devel-2.36.0-5.x86_64             Tue 05 Oct 2021 02:53:16 PM BST
glib-gettextize-2.70.0-1.x86_64               Tue 05 Oct 2021 02:53:16 PM BST
lib64xdmcp-devel-1.1.3-3.x86_64               Tue 05 Oct 2021 02:53:15 PM BST
lib64xcb-devel-1.14-4.x86_64                  Tue 05 Oct 2021 02:53:15 PM BST
lib64xau-devel-1.0.9-4.x86_64                 Tue 05 Oct 2021 02:53:15 PM BST
lib64x11-devel-1.7.2-1.x86_64                 Tue 05 Oct 2021 02:53:15 PM BST
lib64sm-devel-1.2.3-4.x86_64                  Tue 05 Oct 2021 02:53:15 PM BST
pkgconf-1.8.0-1.x86_64                        Tue 05 Oct 2021 02:53:14 PM BST
lib64xcb-xvmc0-1.14-4.x86_64                  Tue 05 Oct 2021 02:53:14 PM BST
lib64xcb-xtest0-1.14-4.x86_64                 Tue 05 Oct 2021 02:53:14 PM BST
lib64xcb-xprint0-1.14-4.x86_64                Tue 05 Oct 2021 02:53:14 PM BST
lib64xcb-xf86dri0-1.14-4.x86_64               Tue 05 Oct 2021 02:53:14 PM BST
lib64xcb-xevie0-1.14-4.x86_64                 Tue 05 Oct 2021 02:53:14 PM BST
lib64xcb-screensaver0-1.14-4.x86_64           Tue 05 Oct 2021 02:53:14 PM BST
lib64pkgconf3-1.8.0-1.x86_64                  Tue 05 Oct 2021 02:53:14 PM BST
lib64dbus-1-devel-1.13.18-5.x86_64            Tue 05 Oct 2021 02:53:14 PM BST
atk1.0-common-2.36.0-5.x86_64                 Tue 05 Oct 2021 02:52:37 PM BST
at-spi2-core-2.42.0-1.x86_64                  Tue 05 Oct 2021 02:50:44 PM BST
at-spi2-atk-2.38.0-3.x86_64                   Tue 05 Oct 2021 02:50:44 PM BST
```

@benbullard79 if you have time, you can try to figure out which package from this list is needed  to start working s-c-p. Unfortunately, today I don't have enough time to deal with it better.

**Comment by AngryPenguinPL** [comment]
fix in progress

**Comment by AngryPenguinPL** [comment]
fixed
