### ISSUE TITLE
Calibre issues error "Bad Database Location"

### ISSUE THREAD

**Issue by christann404** [OpenMandrivaAssociation/distribution#2748]
On startup, calibre (5.25.0-2) issues the error message "Bad Database Location" . Details:

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/main.py", line 327, in initialize_db
    db = LibraryDatabase(self.library_path)
  File "/usr/lib64/calibre/calibre/db/legacy.py", line 187, in __init__
    backend = self.backend = create_backend(library_path, default_prefs=default_prefs,
  File "/usr/lib64/calibre/calibre/db/legacy.py", line 44, in create_backend
    return DB(library_path, default_prefs=default_prefs,
  File "/usr/lib64/calibre/calibre/db/backend.py", line 462, in __init__
    if self.user_version == 0:
  File "/usr/lib64/calibre/calibre/db/backend.py", line 1213, in user_version
    return self.conn.get('pragma user_version;', all=False)
  File "/usr/lib64/calibre/calibre/db/backend.py", line 926, in conn
    self._conn = Connection(self.dbpath)
  File "/usr/lib64/calibre/calibre/db/backend.py", line 341, in __init__
    plugins.load_apsw_extension(self, 'sqlite_extension')
  File "/usr/lib64/calibre/calibre/constants.py", line 324, in load_apsw_extension
    conn.enableloadextension(True)
AttributeError: 'Connection' object has no attribute 'enableloadextension'
[omdv-bug-report-20211017144043.log](https://github.com/OpenMandrivaAssociation/distribution/files/7360629/omdv-bug-report-20211017144043.log)

**Comment by christann404** [comment]
Hi Ben,
That did not help. I think that either something is missing, or it i a clang vs gcc problem. I will try building it locally. 
Chris
