### ISSUE TITLE
dnf search not working (Cooker)

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2799]
**OpenMandriva version**:
Cooker
**Describe the bug**:
running `dnf search >whatever<` is not working.
**Steps to reproduce**:
Open terminal and type `dnf search filelight` or any other search term you wish.
**Observed behavior**:
A traceback that ends with: AttributeError: module 're' has no attribute 'template'
**Expected behavior**:
That `dnf search` would give the normal comprehensive results.
**Additional comment**:

**Logs and screenshots if relevant**
This is Konsole ouput: 
```
$ dnf search filelight

Last metadata expiration check: 3 days, 22:07:24 ago on Mon 23 May 2022 01:32:36 PM CDT.
======================================================================================== Name Exactly Matched: filelight =========================================================================================
Traceback (most recent call last):
  File "/usr/bin/dnf", line 62, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/main.py", line 201, in user_main
    errcode = main(args)
              ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/main.py", line 67, in main
    return _main(base, args, cli_class, option_parser_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/main.py", line 106, in _main
    return cli_run(cli, base)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/main.py", line 122, in cli_run
    cli.run()
    ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/cli.py", line 1057, in run
    return self.command.run()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/commands/search.py", line 160, in run
    return self._search(self.opts.query_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/commands/search.py", line 131, in _search
    self.base.output.matchcallback(pkg, counter.matched_haystacks(pkg), args)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/output.py", line 840, in matchcallback
    msg = self._sub_highlight(msg, highlight, matchfor, ignore_case=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/output.py", line 127, in _sub_highlight
    return self.term.sub(haystack, hibeg, hiend, needles, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/term.py", line 291, in sub
    pat = re.template(pat, re.I)
          ^^^^^^^^^^^
AttributeError: module 're' has no attribute 'template'
```
This is journalctl output: 
[journal.txt](https://github.com/OpenMandrivaAssociation/distribution/files/8788234/journal.txt)

omdv-bug-report.*.log:
[omdv-bug-report-20220527120028.log](https://github.com/OpenMandrivaAssociation/distribution/files/8788239/omdv-bug-report-20220527120028.log)

Running `dnf search` with `sudo` does not change anything. `dnf search` normally works without root privileges.

**Comment by benbullard79** [comment]
Bug confirmed by a user on IRC.
