### ISSUE TITLE
Python 3.11 crashing in MATE desktop while attempting to launch Main Menu editor

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2839]
**OpenMandriva version**: Cooker (in VirtualBox)

**Describe the bug**: Was trying to launch the MATE Main Menu editor, to see if I could change the MATE icon to the OpenMandriva icon. A window tab appeared on the bottom MATE panel, labeled  _Starting Main Menu_, but the menu editor did not appear. When I ran `coredumpctl`, there were only crash reports for Python 3.11, not the Main Menu editor. Attached is the last crash report.

**Steps to reproduce**: Logged into MATE desktop, right-clicked Application at the upper left, selected Edit Menus, window tab appeared as described, then closed.

**Observed behavior**: As above.

**Expected behavior**: Main Menu editor GUI should have appeared.

**Additional information**: 
```

Name         : python
Version      : 3.11.0
Release      : 0.rc1.1
Architecture : x86_64
Size         : 41 M
Source       : python-3.11.0-0.rc1.1.src.rpm
```

**Logs and screenshots if relevant**

```
~]$ coredumpctl debug 1790
           PID: 1790 (mozo)
           UID: 1001 (epp)
           GID: 1007 (epp)
        Signal: 5 (TRAP)
     Timestamp: Thu 2022-09-01 11:26:13 EDT (1min 59s ago)
  Command Line: /usr/bin/python -OOt /usr/bin/mozo
    Executable: /usr/bin/python3.11
 Control Group: /user.slice/user-1001.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1001.slice
       Session: c2
     Owner UID: 1001 (epp)
       Boot ID: e4081e88d7f34615bfa00ada0f3e5d1b
    Machine ID: 671850a9ba124fc1aa73a47625f79294
      Hostname: openmandriva
       Storage: /var/lib/systemd/coredump/core.mozo.1001.e4081e88d7f34615bfa00ada0f3e5d1b.1790.1662045973000000.zst (present)
     Disk Size: 2.7M
       Message: Process 1790 (mozo) of user 1001 dumped core.
                
                Module /usr/lib64/libwayland-cursor.so.0.21.0 with build-id 82eaf0be27c738dcba349e110bb9f71273e9f7c9
                Module linux-vdso.so.1 with build-id ebaf40a5fc1142585d4e0adc354edb8514145f7e
                Module libmd.so.0 with build-id 7956182f909642f5f7de760e5accff8963f90115
                Module liblz4.so.1 with build-id f5863a0c0940c1803a0c70716c962bf11c229c0c
                Module libzstd.so.1 with build-id e65616f0c10f05c239a7ec34a28a8467bebb50f9
                Module libbrotlicommon.so.1 with build-id feb5aacaa6d466c1f3bb0b29159c53d7b5c653e8
                Module libbsd.so.0 with build-id 061d1287d22339eeacca3399148273da0d6d0112
                Module libdatrie.so.1 with build-id e6680d742893931eaa284909d709a2d844e639d0
                Module libsystemd.so.0 with build-id 43e2cdffd08c875165b9341fef598f3c69fe0e9a
                Module libGLX.so.0 with build-id a3552d0ead500135b7484c503d07a47ef5cf42c7
                Module libGLdispatch.so.0 with build-id c01e77cb1526740d69b1510b74e32bcf2f1987b9
                Module libbrotlidec.so.1 with build-id 33e882f54c84001b6f005b652ab3f4054981c1e2
                Module libXdmcp.so.6 with build-id 4a48867e77d717f8cd524cd5bcee6628f83d20a0
                Module libXau.so.6 with build-id 26f206f1182963304371849aed2fce4df1f54466
                Module libgraphite2.so.3 with build-id 4b9a84b5f49305a3c4652cfeaeaba53dbe3a7460
                Module libthai.so.0 with build-id d64fb613a5d16d010c9f9fb610c774e4b2fb9609
                Module libatspi.so.0 with build-id 35577e40e7a2ae647174c266811a83702789e485
                Module libdbus-1.so.3 with build-id e9536818061bbf825fb9e92c54165f9233758773
                Module libintl.so.8 with build-id 00f706085823f82c3000d9fc8928ff77e7dc52f9
                Module libpixman-1.so.0 with build-id 27acc6b5a2fe7eac5f344ae83f41f37fc9ecd44e
                Module libEGL.so.1 with build-id 1b3702a782bf27ce5d1d390222c9bdf280070a2f
                Module libGL.so.1 with build-id 8f8dca64ca9c0e67c99a434b4f4cbdc2dd4e3708
                Module libxcb-shm.so.0 with build-id c27e8520698069ba883967972194a2fd8c03fed1
                Module libxcb-render.so.0 with build-id 0e74d43c0370df98d12e6d6c4fb25a08aeeb41f2
                Module libXrender.so.1 with build-id a8a717995936a3d754d3bfec0d381d340c631669
                Module libfreetype.so.6 with build-id a7f48c83551d8892cd153d59937d378ef8a46d21
                Module libpng16.so.16 with build-id b1829f6abbc89719b9ca84962629a1b1bc5e25f9
                Module libxcb.so.1 with build-id 81dd421d916aff7e4bf3f1770087588d489f5a3a
                Module libXext.so.6 with build-id 351d3549b019fa573ef675b49f4aadcfb169ee09
                Module libwayland-egl.so.1 with build-id 737146756b6a6e05d9d06f5484c2e86e0db98641
                Module libxkbcommon.so.0 with build-id 5d11222144873d7de4e59fa54ec745cf0cad236f
                Module libXdamage.so.1 with build-id 392163d200f32bf59dcd0b25845143e854db848f
                Module libXcomposite.so.1 with build-id ed8e7b0f9c668e28a07c0e76363448560360880d
                Module libXcursor.so.1 with build-id a2defdb818cc2f01d600bb82afdc955abe639c7f
                Module libXrandr.so.2 with build-id 33a08b8fcb9c650e9bdbbd0861e8bacf7df49d61
                Module libXinerama.so.1 with build-id 2ce4f9dbb3288273fae200fb84bfc484f2c21085
                Module libfontconfig.so.1 with build-id 3b39e29b7b472a1f5c3e09bca58388299527fd00
                Module libharfbuzz.so.0 with build-id 8856bc34b01a56ee15184a0501b1f315877323fb
                Module libpango-1.0.so.0 with build-id 0a47c9dfe97633db78e4c828512ec342cb2b5e9c
                Module libpangoft2-1.0.so.0 with build-id 7e9270e13d2e3d74965181ae7c086048878fb56e
                Module libfribidi.so.0 with build-id 1c18cc8eb069247fe88ae62a089ed0d480d3075f
                Module libepoxy.so.0 with build-id 0d2a3805515192aeb0da67a27139759111909c73
                Module libwayland-client.so.0 with build-id e3f67573e5f457e7d892f6ba41a338b3d65147d2
                Module libatk-bridge-2.0.so.0 with build-id 454677790acd51a6a5c6bd0cef6e65566995c49f
                Module libatk-1.0.so.0 with build-id 562d8ed3b66263718f069ca64dc1a5bce7967d41
                Module libgdk_pixbuf-2.0.so.0 with build-id a83ad822c612ab997d10ccaf972a4042a646c622
                Module libcairo.so.2 with build-id 6e4a804c7060496ba19400a458906847319f36cf
                Module libcairo-gobject.so.2 with build-id 3b8bae250cb75b9815c689a5a5f0bea5add89734
                Module libXfixes.so.3 with build-id b76978186aee7a27e7b8a762b2f0c88730eba510
                Module libXi.so.6 with build-id 436152a28a3b8d5807b0d5cac5a416f71ccd98f9
                Module libX11.so.6 with build-id 1b5ac3b2dd8b7e0d781b6ab426c0dc51c6f3963e
                Module libpangocairo-1.0.so.0 with build-id 2ae302f66ccc3eb3d1eedee5a43ca62207898800
                Module libgdk-3.so.0 with build-id 942587bde7396105d5b94640c60b0a7a6881a659
                Module libgtk-3.so.0 with build-id e285cce1785646c1c4b24780924591a2f1c967ec
                Module libexpat.so.1 with build-id b3de6bfd41aa22dc60f5e7173d39dbbec0f7eaea
                Module pyexpat.cpython-311-x86_64-linux-gnu.so with build-id 426457eefefdfba166d9a823ccb9b351d58c8b65
                Module liblzma.so.5 with build-id 9a3c7f6afab1a06aec0800a498085d977cf33fd5
                Module _lzma.cpython-311-x86_64-linux-gnu.so with build-id ac297d22f2a4d064d5272f4c15ee2f67fefc10c1
                Module libbz2.so.1 with build-id e23880ac74f2a27758f64c3619d923c272e1bf61
                Module _bz2.cpython-311-x86_64-linux-gnu.so with build-id 75803a91681dbde66ca0e14f42326f94e33dfb0c
                Module zlib.cpython-311-x86_64-linux-gnu.so with build-id ad9e816686f485a76e2e8f3054da29170a2f97ab
                Module _posixsubprocess.cpython-311-x86_64-linux-gnu.so with build-id 0169bd7b2f372e9ad6d801ed103fc387017b735d
                Module fcntl.cpython-311-x86_64-linux-gnu.so with build-id 097376b05730aa351a7f7a6fecf3255eeb007050
                Module array.cpython-311-x86_64-linux-gnu.so with build-id cf068bf7a8fca31dd40442280776f1837a7c617d
                Module select.cpython-311-x86_64-linux-gnu.so with build-id a610bb996bc03ebbe3fd837948310a91ed3df5c6
                Module math.cpython-311-x86_64-linux-gnu.so with build-id 56a580a3318eb4cf5a32f0dc8be1dbdea2dd19e6
                Module _socket.cpython-311-x86_64-linux-gnu.so with build-id d525e665b1f94d658868af0533cd900cdd68d5dc
                Module libgpg-error.so.0 with build-id a6680da9d7245901f1ff24a100bf5425ee1b5f60
                Module libudev.so.1 with build-id 106cc37a00eaa81b910d09daa7b2a4a0b7af95c8
                Module libjson-c.so.5 with build-id 873427cccc5d145a097edf2b6ef3193b4ccf972a
                Module libargon2.so.1 with build-id 3880e4a7a995458b5c286493607f64bef8fc69e9
                Module libgcrypt.so.20 with build-id 67e4534d1621d33e080c174beacc64cafdb94b5e
                Module libdevmapper.so.1.02 with build-id 61c1e5e4ffe2289faf855cf428ef789412e38908
                Module libuuid.so.1 with build-id 44037f1c32821bba724abe306289c676cbbc5b73
                Module libcryptsetup.so.12 with build-id 35a751f866c189a0a09a15c4f2ff8c0a7fd02815
                Module libblkid.so.1 with build-id 139dd673bf37383ad271a5b23457058ee22c6d35
                Module libmount.so.1 with build-id d3ae7c9d96893eee9db4a189b9b027115fa406b0
                Module libz.so.1 with build-id f2f72dd4e051d1b984550ab6514de7cdcf574e40
                Module libgio-2.0.so.0 with build-id 6398a752e5ffae0d14bb179a1adbca6302fe02e4
                Module libgmodule-2.0.so.0 with build-id a1f216293bf3e1d4b37c152d51360405a16d3de4
                Module libpcre.so.1 with build-id e2a7a77db4df67536181717c341f61baaab74bc8
                Module libffi.so.8 with build-id 2af3e1d6e6cd3f40c51986a4925de4ce3bac6c24
                Module libgobject-2.0.so.0 with build-id ed20c1e413f012e79c5192ba38eea3b9d55815cd
                Module libgirepository-1.0.so.1 with build-id 8a68a7fabfa55855626588815b404b886bfbcd18
                Module libglib-2.0.so.0 with build-id b0046b3b1d7decde918b8454ec084df141bbaeb4
                Module _gi.cpython-311-x86_64-linux-gnu.so with build-id d98e3deae638af04eeb347b171709ec905599b7e
                Module _typing.cpython-311-x86_64-linux-gnu.so with build-id 93e36e9f3015dacdb141850d349d612614a35b11
                Module ld-linux-x86-64.so.2 with build-id 5fd304013c78f64c4739ea26d4c60ae089c39628
                Module libm.so.6 with build-id a891ad1e9b3305e267537eb2aa71e7ca3d931cf6
                Module libc.so.6 with build-id 50cceb6765d70f9fd5c3a23c510b4c8c49fdbbfc
                Module libpython3.11.so.1.0 with build-id 4b4f2f0f40d567715ae6c250fbef0190855ba1af
                Module python3.11 with build-id d9e307c3d4e4c7d44987142b5564aef79d3dc082
                Stack trace of thread 1790:
                #0  0x00007f57cc412aec n/a (libgtk-3.so.0 + 0x612aec)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 12.1-2 (OpenMandriva Lx release 4.90)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-openmandriva-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
/etc/gdbinit:9: Error in sourced command file:
Scripting in the "Python" language is not supported in this copy of GDB.
Reading symbols from /usr/bin/python3.11...
Reading symbols from .gnu_debugdata for /usr/bin/python3.11...
(No debugging symbols found in .gnu_debugdata for /usr/bin/python3.11)
[New LWP 1790]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/python -OOt /usr/bin/mozo'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f57cc412aec in ?? () from /lib64/libgtk-3.so.0
(gdb) bt full
#0  0x00007f57cc412aec in ?? () from /lib64/libgtk-3.so.0
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) 


```

**Comment by mandian** [comment]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/python -OOt /usr/bin/mozo'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f57cc412aec in ?? () from /lib64/libgtk-3.so.0
(gdb) bt full
#0  0x00007f57cc412aec in ?? () from /lib64/libgtk-3.so.0
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) 

```
Maybe it is just mozo. Please could you retry with latest updates (should install mozo-1.26.1-5)?

**Comment by edwardp3** [comment]
```
~]$ rpm -q mozo
mozo-1.26.1-5.noarch
```

```
~]$ coredumpctl debug 1322
           PID: 1322 (mozo)
           UID: 1001 (epp)
           GID: 1007 (epp)
        Signal: 5 (TRAP)
     Timestamp: Thu 2022-10-20 08:53:03 EDT (3min 29s ago)
  Command Line: /usr/bin/python -OOt /usr/bin/mozo
    Executable: /usr/bin/python3.11
 Control Group: /user.slice/user-1001.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1001.slice
       Session: c2
     Owner UID: 1001 (epp)
       Boot ID: f693e99704e440a9bdc44c943f919deb
    Machine ID: 143ea031d276403498362748fa2de08d
      Hostname: omvmate
       Storage: /var/lib/systemd/coredump/core.mozo.1001.f693e99704e440a9bdc44c943f919deb.1322.1666270383000000.zst (present)
     Disk Size: 2.7M
       Message: Process 1322 (mozo) of user 1001 dumped core.
                
                Module linux-vdso.so.1 with build-id 642bac8ed08c258814b1b1b9881f60c2fa6ee650
                Module libmd.so.0 with build-id 7956182f909642f5f7de760e5accff8963f90115
                Module liblz4.so.1 with build-id f5863a0c0940c1803a0c70716c962bf11c229c0c
                Module libzstd.so.1 with build-id bacb03e16c48b91d5e5af185b48d5f5aa4e88b97
                Module libbrotlicommon.so.1 with build-id feb5aacaa6d466c1f3bb0b29159c53d7b5c653e8
                Module libbsd.so.0 with build-id 92c31a31c4d9a112f37cb6c194caa25b4e8cbc1d
                Module libdatrie.so.1 with build-id e6680d742893931eaa284909d709a2d844e639d0
                Module libsystemd.so.0 with build-id 53ddc294137b5ca28b981053bb4b9de781c7a216
                Module libGLX.so.0 with build-id a3552d0ead500135b7484c503d07a47ef5cf42c7
                Module libGLdispatch.so.0 with build-id c01e77cb1526740d69b1510b74e32bcf2f1987b9
                Module libbrotlidec.so.1 with build-id 33e882f54c84001b6f005b652ab3f4054981c1e2
                Module libXdmcp.so.6 with build-id 4a48867e77d717f8cd524cd5bcee6628f83d20a0
                Module libXau.so.6 with build-id 26f206f1182963304371849aed2fce4df1f54466
                Module libgraphite2.so.3 with build-id 4b9a84b5f49305a3c4652cfeaeaba53dbe3a7460
                Module libthai.so.0 with build-id d64fb613a5d16d010c9f9fb610c774e4b2fb9609
                Module libatspi.so.0 with build-id 35577e40e7a2ae647174c266811a83702789e485
                Module libdbus-1.so.3 with build-id dd10fa2f31eb294043ebe9a86bf46e301896ccc0
                Module libintl.so.8 with build-id 00f706085823f82c3000d9fc8928ff77e7dc52f9
                Module libpixman-1.so.0 with build-id 6a61b77913c5c6f642bc62aa72ce61afe3dfa255
                Module libEGL.so.1 with build-id 1b3702a782bf27ce5d1d390222c9bdf280070a2f
                Module libGL.so.1 with build-id 8f8dca64ca9c0e67c99a434b4f4cbdc2dd4e3708
                Module libxcb-shm.so.0 with build-id c27e8520698069ba883967972194a2fd8c03fed1
                Module libxcb-render.so.0 with build-id 0e74d43c0370df98d12e6d6c4fb25a08aeeb41f2
                Module libXrender.so.1 with build-id a8a717995936a3d754d3bfec0d381d340c631669
                Module libfreetype.so.6 with build-id a7f48c83551d8892cd153d59937d378ef8a46d21
                Module libpng16.so.16 with build-id 6f41b0d12afd5d4d94be569cdce0a54a08f7580a
                Module libxcb.so.1 with build-id 81dd421d916aff7e4bf3f1770087588d489f5a3a
                Module libXext.so.6 with build-id 351d3549b019fa573ef675b49f4aadcfb169ee09
                Module libwayland-egl.so.1 with build-id 737146756b6a6e05d9d06f5484c2e86e0db98641
                Module libwayland-cursor.so.0 with build-id 82eaf0be27c738dcba349e110bb9f71273e9f7c9
                Module libxkbcommon.so.0 with build-id 5d11222144873d7de4e59fa54ec745cf0cad236f
                Module libXdamage.so.1 with build-id 392163d200f32bf59dcd0b25845143e854db848f
                Module libXcomposite.so.1 with build-id ed8e7b0f9c668e28a07c0e76363448560360880d
                Module libXcursor.so.1 with build-id a2defdb818cc2f01d600bb82afdc955abe639c7f
                Module libXrandr.so.2 with build-id 33a08b8fcb9c650e9bdbbd0861e8bacf7df49d61
                Module libXinerama.so.1 with build-id 2ce4f9dbb3288273fae200fb84bfc484f2c21085
                Module libfontconfig.so.1 with build-id 7c2224402eb3b52dc73877826292d714bd1a215b
                Module libharfbuzz.so.0 with build-id c6a1f6e803cc0212ccbe186ae83afa1daf79f542
                Module libpango-1.0.so.0 with build-id 0354845d8a3639ad0c90a53e032b6aa6fe9eb1b2
                Module libpangoft2-1.0.so.0 with build-id 900930b61cd46550c9dd24d654e60bf9e9251af8
                Module libfribidi.so.0 with build-id 1c18cc8eb069247fe88ae62a089ed0d480d3075f
                Module libepoxy.so.0 with build-id e40a2bb7d2645fe5b545b9e1bd5a8f550efd9906
                Module libwayland-client.so.0 with build-id e3f67573e5f457e7d892f6ba41a338b3d65147d2
                Module libatk-bridge-2.0.so.0 with build-id 454677790acd51a6a5c6bd0cef6e65566995c49f
                Module libatk-1.0.so.0 with build-id 562d8ed3b66263718f069ca64dc1a5bce7967d41
                Module libgdk_pixbuf-2.0.so.0 with build-id 9d16d2ab9bb5e37ce48a90c6a46d10e4aecf7df5
                Module libcairo.so.2 with build-id 3b1c3241847aec91ce648da57b8699f74af214b0
                Module libcairo-gobject.so.2 with build-id 8a6dca99aabfb32a0d74aa3ca7633388b5fc6f70
                Module libXfixes.so.3 with build-id b76978186aee7a27e7b8a762b2f0c88730eba510
                Module libXi.so.6 with build-id 436152a28a3b8d5807b0d5cac5a416f71ccd98f9
                Module libX11.so.6 with build-id 1b5ac3b2dd8b7e0d781b6ab426c0dc51c6f3963e
                Module libpangocairo-1.0.so.0 with build-id e104d5cbd452a23dee5bb655c5f5907355255145
                Module libgdk-3.so.0 with build-id 342d71f30076ba27ce36c2a202f1ef55de09d853
                Module libgtk-3.so.0 with build-id 797e347268491d6a2d431af15e2d328b741cd426
                Module libexpat.so.1 with build-id 311d06153905bfce25680973f67d51190027210c
                Module pyexpat.cpython-311-x86_64-linux-gnu.so with build-id 0c05dca463af0ea9a17b869a7a3883c1d59511dc
                Module liblzma.so.5 with build-id 9a3c7f6afab1a06aec0800a498085d977cf33fd5
                Module _lzma.cpython-311-x86_64-linux-gnu.so with build-id bc4550d7fdcf8ac019433d818b84be1c3034e8c7
                Module libbz2.so.1 with build-id e23880ac74f2a27758f64c3619d923c272e1bf61
                Module _bz2.cpython-311-x86_64-linux-gnu.so with build-id a22a82f51cd78bfe90bb8b75c8667d811eb6068c
                Module zlib.cpython-311-x86_64-linux-gnu.so with build-id 3ad7a9dada481ca38a05a6fce4dc51efe77c3ae2
                Module _posixsubprocess.cpython-311-x86_64-linux-gnu.so with build-id ba966d36823e08300456bff9d302bdc348575fb5
                Module fcntl.cpython-311-x86_64-linux-gnu.so with build-id bb736469459b2cbb61f6085c09c839344d02a15b
                Module array.cpython-311-x86_64-linux-gnu.so with build-id 157e1fda03b11c3e785d8803333a74e894a56030
                Module select.cpython-311-x86_64-linux-gnu.so with build-id 9436e7dd3aaf0a05b3993b78f154936db34fff56
                Module math.cpython-311-x86_64-linux-gnu.so with build-id 29471cdf7447668e178eedebb6f29c4377341d6c
                Module _socket.cpython-311-x86_64-linux-gnu.so with build-id 9e91e4973d01f927adb647d3d4a7f332d62af246
                Module libgpg-error.so.0 with build-id a6680da9d7245901f1ff24a100bf5425ee1b5f60
                Module libudev.so.1 with build-id dcddf71ea951b969dfaa4b1f2221ab37ae7a87df
                Module libjson-c.so.5 with build-id 873427cccc5d145a097edf2b6ef3193b4ccf972a
                Module libargon2.so.1 with build-id 3880e4a7a995458b5c286493607f64bef8fc69e9
                Module libgcrypt.so.20 with build-id 67e4534d1621d33e080c174beacc64cafdb94b5e
                Module libdevmapper.so.1.02 with build-id 61c1e5e4ffe2289faf855cf428ef789412e38908
                Module libuuid.so.1 with build-id 44037f1c32821bba724abe306289c676cbbc5b73
                Module libcryptsetup.so.12 with build-id 35a751f866c189a0a09a15c4f2ff8c0a7fd02815
                Module libblkid.so.1 with build-id 139dd673bf37383ad271a5b23457058ee22c6d35
                Module libmount.so.1 with build-id d3ae7c9d96893eee9db4a189b9b027115fa406b0
                Module libz.so.1 with build-id 76d51349c508b76d90f3f35e8d54cba723c47c38
                Module libgio-2.0.so.0 with build-id 1e4d60b77ec4a500d514494f2b8d74fd4c0ed44b
                Module libgmodule-2.0.so.0 with build-id 549b4186d522c7990e7b9c7663d61750ec2b4bd0
                Module libpcre2-8.so.0 with build-id 457eecd24a76494da50827c18dbf4cd79c44a676
                Module libffi.so.8 with build-id d834e84fe9aa3a9304df93185547a3d83ecd079c
                Module libgobject-2.0.so.0 with build-id 1b609ec77d404be652e2e385368e96bcca355bb3
                Module libgirepository-1.0.so.1 with build-id 79f79661ff20773701576d44c5df4a0575caa9a2
                Module libglib-2.0.so.0 with build-id 36b3f3c6004c217f8c0375f549e2dd1af379a7af
                Module _gi.cpython-311-x86_64-linux-gnu.so with build-id 3b088e6a6ea29ffd3214cccb56c3a910b7dde891
                Module _typing.cpython-311-x86_64-linux-gnu.so with build-id bec25d1d260749fba41af482bbe11ba19adf41ca
                Module ld-linux-x86-64.so.2 with build-id 7010a99ab30861cb92a1776c7ac5495eeaaac620
                Module libm.so.6 with build-id 6edf3f6736ef3b5130a6ae5e32abb6cbc3a12c02
                Module libc.so.6 with build-id 7c69eae22dc9a007fcbbd97884088e22551d9e6a
                Module libpython3.11.so.1.0 with build-id 8e8f918cc8bd3b091f4968a0c4fe74c7c2907102
                Module python3.11 with build-id ff5ccde3034fd4c114395d013c44bab9d8b8ca11
                Stack trace of thread 1322:
                #0  0x00007f7d5e61157c n/a (libgtk-3.so.0 + 0x61157c)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 12.1-2 (OpenMandriva Lx release 4.90)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-openmandriva-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
/etc/gdbinit:9: Error in sourced command file:
Scripting in the "Python" language is not supported in this copy of GDB.
Reading symbols from /usr/bin/python3.11...
Reading symbols from .gnu_debugdata for /usr/bin/python3.11...
(No debugging symbols found in .gnu_debugdata for /usr/bin/python3.11)
[New LWP 1322]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/python -OOt /usr/bin/mozo'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f7d5e61157c in ?? () from /lib64/libgtk-3.so.0
(gdb) bt full
#0  0x00007f7d5e61157c in ?? () from /lib64/libgtk-3.so.0
No symbol table info available.
#1  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) 

```

**Comment by benbullard79** [comment]
Not sure what to say other than the OP told us he would not use OMLx anymore.
