### ISSUE TITLE
Firefox 104.0.1 froze on OpenMandriva Forum home page

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2843]
**OpenMandriva version**: Rolling

**Describe the bug**: Was logged into OM Forum when Firefox froze. Also had a YouTube tab open (music with static video) before the freeze.

**Steps to reproduce**: Logged into to OM Forum, also had a YouTube tab in the browser. Firefox eventually froze. Attempted to close YouTube tab to see if it freed up any resources, yet Firefox was still frozen.

**Observed behavior**: Firefox UI froze. Scrolling with the mouse had no effect, until the page eventually 'thawed' then froze again. Had to `ps -e -9 `to kill the job, in order to exit Firefox.

**Expected behavior**: Firefox UI should have remained responsive.

**Additional comment**: In the screenshot below, you can see where the YouTube tab was previously situated in the UI. Also mentioned in exisating thread here: https://forum.openmandriva.org/t/issues-with-installed-rolling-firefox-audio-usb-bluetooth/4645/8

**Logs and screenshots if relevant**

![firefox-freeze](https://user-images.githubusercontent.com/73129450/189486953-f6a28913-5420-45b2-bb26-79403d7b5cf5.png)

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/issues-with-installed-rolling-firefox-audio-usb-bluetooth/4645/8

**Comment by edwardp3** [comment]
Had another crash, but in VirftualBox and on this site, unknown if related:

```
~]$ coredumpctl debug 4281
           PID: 4281 (Isolated Web Co)
           UID: 1001 (epp)
           GID: 1006 (epp)
        Signal: 11 (SEGV)
     Timestamp: Mon 2022-09-12 09:58:35 EDT (6min ago)
  Command Line: /usr/lib64/firefox-104.0.1/firefox -contentproc -childID 4 -isForBrowser -prefsLen 31849 -prefMapSize 227499 -jsInitLen 247488 -parentBuildID 20220831094136 -appDir /usr/lib64/firefox-104.0.1/browser 4108 tab
    Executable: /usr/lib64/firefox-104.0.1/firefox
 Control Group: /user.slice/user-1001.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1001.slice
       Session: c2
     Owner UID: 1001 (epp)
       Boot ID: 1eaac0550d524815b456551421c1a2dc
    Machine ID: 0460466aee274ea68e396bd7ce2813f3
      Hostname: openmandriva
       Storage: /var/lib/systemd/coredump/core.Isolated\x20Web\x20Co.1001.1eaac0550d524815b456551421c1a2dc.4281.1662991115000000.zst (present)
     Disk Size: 4.5M
       Message: Process 4281 (Isolated Web Co) of user 1001 dumped core.
                
                Module /usr/lib64/libdbus-glib-1.so.2.3.5 with build-id 718965320183fd1881eff6b175866d0ebf3e6394
                Module /usr/lib64/libXdamage.so.1.1.0 with build-id 392163d200f32bf59dcd0b25845143e854db848f
                Module /usr/lib64/firefox-104.0.1/libmozwayland.so with build-id 1f031f30660aeae43e287666df7f77727b14ddaf
                Module /usr/lib64/firefox-104.0.1/libmozsandbox.so with build-id 9dd68ad7a3ec39b8786e8a9fd11b5c8d569c969a
                Module linux-vdso.so.1 with build-id aab1b64e3f9e6fcffde1827df8865d478a187d81
                Module libfreeblpriv3.so with build-id 8a892b4fe3f23a50add9ad5ba8229b9e611f9005
                Module libsqlite3.so.0 with build-id 658f90dbb01230adfd36c9973c25295342bb35ed
                Module libsoftokn3.so with build-id 846c91a20e99f6c13de2d9efde424e180475845c
                Module libplds4.so with build-id 10dff76f3d728f736ecb41a96dccd6bc1e6707ea
                Module libicudata.so.71 with build-id f75c971cc0fee7b4ba0666c18e631019133127ca
                Module libproxy.so.1 with build-id 3b03a260fbef0ff099d2c0b3dc6761ce7bfd9360
                Module libX11-xcb.so.1 with build-id 7b69e1709ac2076cfef565b64db343f5cec5bf32
                Module libvpx.so.7 with build-id 85d185613fb2d5f4450ae48e54c8c742edf2188b
                Module libnssutil3.so with build-id 034ca38f6882741c098148e3e878daae82898bbd
                Module libnss3.so with build-id 0c07f18bc88219f475afedd9baf98cee8a14d0c7
                Module libsmime3.so with build-id 67d4068686bab2614daaf552005b210e869558a8
                Module libssl3.so with build-id ca10ff517d09402bc50e2e3c6ed9d2812962cd95
                Module libplc4.so with build-id 38bec3958ec110fd32ceb8580e35f26b5be8500a
                Module libasound.so.2 with build-id 2d2ad2b4feffc89cc11c2007d933841e4d02d1e5
                Module libicuuc.so.71 with build-id 485f4527471d21f52206b3c6dd8576c33dd776aa
                Module libicui18n.so.71 with build-id eb9638dc22fe1c81b90acd9e1ae226d828acd84a
                Module libxul.so with build-id 17e1addf5bfe321e0c2ee6c694d23dc88f6e3676
                Module libudev.so.1 with build-id 106cc37a00eaa81b910d09daa7b2a4a0b7af95c8
                Module libgpg-error.so.0 with build-id a6680da9d7245901f1ff24a100bf5425ee1b5f60
                Module libmd.so.0 with build-id 7956182f909642f5f7de760e5accff8963f90115
                Module libjson-c.so.5 with build-id 873427cccc5d145a097edf2b6ef3193b4ccf972a
                Module libargon2.so.1 with build-id 3880e4a7a995458b5c286493607f64bef8fc69e9
                Module libdevmapper.so.1.02 with build-id 61c1e5e4ffe2289faf855cf428ef789412e38908
                Module liblz4.so.1 with build-id f5863a0c0940c1803a0c70716c962bf11c229c0c
                Module libzstd.so.1 with build-id e1eaf95381b34704f91ce0fc6cfbca88e98b8093
                Module liblzma.so.5 with build-id 9a3c7f6afab1a06aec0800a498085d977cf33fd5
                Module libgcrypt.so.20 with build-id 67e4534d1621d33e080c174beacc64cafdb94b5e
                Module libbrotlicommon.so.1 with build-id feb5aacaa6d466c1f3bb0b29159c53d7b5c653e8
                Module libbsd.so.0 with build-id 061d1287d22339eeacca3399148273da0d6d0112
                Module libdatrie.so.1 with build-id e6680d742893931eaa284909d709a2d844e639d0
                Module libcryptsetup.so.12 with build-id 35a751f866c189a0a09a15c4f2ff8c0a7fd02815
                Module libblkid.so.1 with build-id 139dd673bf37383ad271a5b23457058ee22c6d35
                Module libsystemd.so.0 with build-id 43e2cdffd08c875165b9341fef598f3c69fe0e9a
                Module libGLX.so.0 with build-id a3552d0ead500135b7484c503d07a47ef5cf42c7
                Module libGLdispatch.so.0 with build-id c01e77cb1526740d69b1510b74e32bcf2f1987b9
                Module libbrotlidec.so.1 with build-id 33e882f54c84001b6f005b652ab3f4054981c1e2
                Module libbz2.so.1 with build-id e23880ac74f2a27758f64c3619d923c272e1bf61
                Module libXdmcp.so.6 with build-id 4a48867e77d717f8cd524cd5bcee6628f83d20a0
                Module libXau.so.6 with build-id 26f206f1182963304371849aed2fce4df1f54466
                Module libuuid.so.1 with build-id 44037f1c32821bba724abe306289c676cbbc5b73
                Module libexpat.so.1 with build-id b3de6bfd41aa22dc60f5e7173d39dbbec0f7eaea
                Module libgraphite2.so.3 with build-id 4b9a84b5f49305a3c4652cfeaeaba53dbe3a7460
                Module libpcre.so.1 with build-id e2a7a77db4df67536181717c341f61baaab74bc8
                Module libthai.so.0 with build-id d64fb613a5d16d010c9f9fb610c774e4b2fb9609
                Module libmount.so.1 with build-id d3ae7c9d96893eee9db4a189b9b027115fa406b0
                Module libffi.so.8 with build-id 2af3e1d6e6cd3f40c51986a4925de4ce3bac6c24
                Module libatspi.so.0 with build-id 35577e40e7a2ae647174c266811a83702789e485
                Module libdbus-1.so.3 with build-id e9536818061bbf825fb9e92c54165f9233758773
                Module libintl.so.8 with build-id 00f706085823f82c3000d9fc8928ff77e7dc52f9
                Module libpixman-1.so.0 with build-id 39e6aaae0fd9bfd34e83df7695b9183df07348b9
                Module libEGL.so.1 with build-id 1b3702a782bf27ce5d1d390222c9bdf280070a2f
                Module libGL.so.1 with build-id 8f8dca64ca9c0e67c99a434b4f4cbdc2dd4e3708
                Module libxcb-shm.so.0 with build-id c27e8520698069ba883967972194a2fd8c03fed1
                Module libxcb-render.so.0 with build-id 0e74d43c0370df98d12e6d6c4fb25a08aeeb41f2
                Module libXrender.so.1 with build-id a8a717995936a3d754d3bfec0d381d340c631669
                Module libfreetype.so.6 with build-id a7f48c83551d8892cd153d59937d378ef8a46d21
                Module libpng16.so.16 with build-id 5e3cf4926e49fbb6a91c4d11aaff80a7e9ee5d5b
                Module libz.so.1 with build-id e311fd7964b9ccc8c166cac358b9b929a716a8b4
                Module libxcb.so.1 with build-id 81dd421d916aff7e4bf3f1770087588d489f5a3a
                Module libXext.so.6 with build-id 351d3549b019fa573ef675b49f4aadcfb169ee09
                Module libwayland-egl.so.1 with build-id 737146756b6a6e05d9d06f5484c2e86e0db98641
                Module libwayland-cursor.so.0 with build-id 82eaf0be27c738dcba349e110bb9f71273e9f7c9
                Module libxkbcommon.so.0 with build-id 5d11222144873d7de4e59fa54ec745cf0cad236f
                Module libXcomposite.so.1 with build-id ed8e7b0f9c668e28a07c0e76363448560360880d
                Module libXcursor.so.1 with build-id a2defdb818cc2f01d600bb82afdc955abe639c7f
                Module libXrandr.so.2 with build-id 33a08b8fcb9c650e9bdbbd0861e8bacf7df49d61
                Module libXinerama.so.1 with build-id 2ce4f9dbb3288273fae200fb84bfc484f2c21085
                Module libfontconfig.so.1 with build-id 3b39e29b7b472a1f5c3e09bca58388299527fd00
                Module libharfbuzz.so.0 with build-id 8856bc34b01a56ee15184a0501b1f315877323fb
                Module libglib-2.0.so.0 with build-id b0046b3b1d7decde918b8454ec084df141bbaeb4
                Module libgobject-2.0.so.0 with build-id ed20c1e413f012e79c5192ba38eea3b9d55815cd
                Module libpango-1.0.so.0 with build-id 0a47c9dfe97633db78e4c828512ec342cb2b5e9c
                Module libpangoft2-1.0.so.0 with build-id 7e9270e13d2e3d74965181ae7c086048878fb56e
                Module libgio-2.0.so.0 with build-id 6398a752e5ffae0d14bb179a1adbca6302fe02e4
                Module libfribidi.so.0 with build-id 1c18cc8eb069247fe88ae62a089ed0d480d3075f
                Module libepoxy.so.0 with build-id 0d2a3805515192aeb0da67a27139759111909c73
                Module libwayland-client.so.0 with build-id e3f67573e5f457e7d892f6ba41a338b3d65147d2
                Module libatk-bridge-2.0.so.0 with build-id 454677790acd51a6a5c6bd0cef6e65566995c49f
                Module libatk-1.0.so.0 with build-id 562d8ed3b66263718f069ca64dc1a5bce7967d41
                Module libgdk_pixbuf-2.0.so.0 with build-id a83ad822c612ab997d10ccaf972a4042a646c622
                Module libcairo.so.2 with build-id 6e4a804c7060496ba19400a458906847319f36cf
                Module libcairo-gobject.so.2 with build-id 3b8bae250cb75b9815c689a5a5f0bea5add89734
                Module libXfixes.so.3 with build-id b76978186aee7a27e7b8a762b2f0c88730eba510
                Module libXi.so.6 with build-id 436152a28a3b8d5807b0d5cac5a416f71ccd98f9
                Module libX11.so.6 with build-id 1b5ac3b2dd8b7e0d781b6ab426c0dc51c6f3963e
                Module libpangocairo-1.0.so.0 with build-id 2ae302f66ccc3eb3d1eedee5a43ca62207898800
                Module libgmodule-2.0.so.0 with build-id a1f216293bf3e1d4b37c152d51360405a16d3de4
                Module libgdk-3.so.0 with build-id 942587bde7396105d5b94640c60b0a7a6881a659
                Module libgtk-3.so.0 with build-id e285cce1785646c1c4b24780924591a2f1c967ec
                Module libmozgtk.so with build-id a25285200a9cf99b3f28550e6e5c53fd798f3fa6
                Module libmozsqlite3.so with build-id d00374569bfb47600e66830007661cb8559dd024
                Module liblgpllibs.so with build-id c0883a467e88c8380b051c63bfad12403050317d
                Module libgcc_s.so.1 with build-id fae439cd4fd54bb7d5560dcad0483996b5e108f1
                Module libnspr4.so with build-id 335ff82c31c705a152fe341e989717bea0abc24b
                Module ld-linux-x86-64.so.2 with build-id 5fd304013c78f64c4739ea26d4c60ae089c39628
                Module libc.so.6 with build-id 50cceb6765d70f9fd5c3a23c510b4c8c49fdbbfc
                Module libm.so.6 with build-id a891ad1e9b3305e267537eb2aa71e7ca3d931cf6
                Module libstdc++.so.6 with build-id f78db9bc20929f978ef1350188541d01d30683b7
                Module firefox with build-id ea5b39a0b775d060579c1811b437c6f7b7198fe2
                Stack trace of thread 4281:
                #0  0x00007f5af676bf83 _ZN7mozilla3net16HttpChannelChild13AsyncCallImplEMS1_FvvEPP16nsRunnableMethodIS1_vLb1ELNS_12RunnableKindE0EE (libxul.so + 0x236bf83)
                #1  0x00007f5af678baad _ZThn1456_N7mozilla3net16HttpChannelChild9AsyncCallEMS1_FvvEPP16nsRunnableMethodIS1_vLb1ELNS_12RunnableKindE0EE (libxul.so + 0x238baad)
                #2  0x00007f5af676377e _ZN7mozilla3net16HttpAsyncAborterINS0_16HttpChannelChildEE10AsyncAbortE8nsresult (libxul.so + 0x236377e)
                #3  0x00007f5af675f6e7 _ZN7mozilla3net16HttpChannelChild6CancelE8nsresult (libxul.so + 0x235f6e7)
                #4  0x00007f5af676714a _ZThn120_N7mozilla3net16HttpChannelChild6CancelE8nsresult (libxul.so + 0x236714a)
                #5  0x00007f5af65a1c98 _ZN7mozilla3net11nsLoadGroup6CancelE8nsresult (libxul.so + 0x21a1c98)
                #6  0x00007f5af6b23f02 _ZN11nsDocLoader4StopEv (libxul.so + 0x2723f02)
                #7  0x00007f5af6b22dd5 _ZN11nsDocLoader7DestroyEv (libxul.so + 0x2722dd5)
                #8  0x00007f5af6b22bd9 _ZN11nsDocLoaderD2Ev (libxul.so + 0x2722bd9)
                #9  0x00007f5af9c7a7a7 _ZN10nsDocShellD2Ev (libxul.so + 0x587a7a7)
                #10 0x00007f5af9c7abcb _ZN10nsDocShellD0Ev (libxul.so + 0x587abcb)
                #11 0x00007f5af6b2366a _ZN11nsDocLoader22DeleteCycleCollectableEv (libxul.so + 0x272366a)
                #12 0x00007f5af65f732a _ZN7mozilla3net12nsUDPMessage15cycleCollection22DeleteCycleCollectableEPv (libxul.so + 0x21f732a)
                #13 0x00007f5af63db95a _ZN15SnowWhiteKillerD2Ev (libxul.so + 0x1fdb95a)
                #14 0x00007f5af63db1f8 _ZN16nsCycleCollector13FreeSnowWhiteEb (libxul.so + 0x1fdb1f8)
                #15 0x00007f5af63de8ab _ZN16nsCycleCollector15BeginCollectionEN7mozilla8CCReasonE10ccIsManualP25nsICycleCollectorListener (libxul.so + 0x1fde8ab)
                #16 0x00007f5af63de3f8 _ZN16nsCycleCollector7CollectEN7mozilla8CCReasonE10ccIsManualRN2js11SliceBudgetEP25nsICycleCollectorListenerb (libxul.so + 0x1fde3f8)
                #17 0x00007f5af63de1db _ZN16nsCycleCollector15ShutdownCollectEv (libxul.so + 0x1fde1db)
                #18 0x00007f5af63dfd63 _Z25nsCycleCollector_shutdownb (libxul.so + 0x1fdfd63)
                #19 0x00007f5af649bd9c _ZN7mozilla13ShutdownXPCOMEP17nsIServiceManager (libxul.so + 0x209bd9c)
                #20 0x00007f5af649bad6 NS_ShutdownXPCOM (libxul.so + 0x209bad6)
                #21 0x00007f5afa10bcdf _Z17XRE_TermEmbeddingv (libxul.so + 0x5d0bcdf)
                #22 0x00007f5af69bba30 _ZN7mozilla3ipc14ScopedXREEmbed4StopEv (libxul.so + 0x25bba30)
                #23 0x00007f5af88cb62d _ZN7mozilla3dom14ContentProcess7CleanUpEv (libxul.so + 0x44cb62d)
                #24 0x00007f5afa10c389 _Z20XRE_InitChildProcessiPPcPK12XREChildData (libxul.so + 0x5d0c389)
                #25 0x00007f5afa11259e _ZN7mozilla13BootstrapImpl20XRE_InitChildProcessEiPPcPK12XREChildData (libxul.so + 0x5d1259e)
                #26 0x0000558787afb2d2 main (firefox + 0x1f2d2)
                #27 0x00007f5aff0421ca __libc_start_call_main (libc.so.6 + 0x231ca)
                #28 0x00007f5aff042285 __libc_start_main (libc.so.6 + 0x23285)
                #29 0x0000558787afaf01 _start (firefox + 0x1ef01)
                
                Stack trace of thread 4285:
                #0  0x00007f5aff11c349 syscall (libc.so.6 + 0xfd349)
                #1  0x00007f5af697ce7e epoll_dispatch (libxul.so + 0x257ce7e)
                #2  0x00007f5af6980283 event_base_loop (libxul.so + 0x2580283)
                #3  0x00007f5af6961c68 _ZN4base19MessagePumpLibevent3RunEPNS_11MessagePump8DelegateE (libxul.so + 0x2561c68)
                #4  0x00007f5af695fd18 _ZN11MessageLoop3RunEv (libxul.so + 0x255fd18)
                #5  0x00007f5af6969713 _ZN4base6Thread10ThreadMainEv (libxul.so + 0x2569713)
                #6  0x00007f5af6966b37 _ZL10ThreadFuncPv (libxul.so + 0x2566b37)
                #7  0x00007f5aff0a40b6 start_thread (libc.so.6 + 0x850b6)
                #8  0x00007f5aff12432c __clone3 (libc.so.6 + 0x10532c)
                
                Stack trace of thread 4295:
                #0  0x00007f5aff0a0e56 __futex_abstimed_wait_common (libc.so.6 + 0x81e56)
                #1  0x00007f5aff0a3528 pthread_cond_wait (libc.so.6 + 0x84528)
                #2  0x0000558787b43639 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (firefox + 0x67639)
                #3  0x00007f5af64638a5 _ZN7mozilla14TaskController13RunPoolThreadEv (libxul.so + 0x20638a5)
                #4  0x00007f5af64636d1 _ZN7mozilla20ThreadFuncPoolThreadEPv (libxul.so + 0x20636d1)
                #5  0x00007f5aff014605 _pt_root (libnspr4.so + 0x45605)
                #6  0x00007f5aff0a40b6 start_thread (libc.so.6 + 0x850b6)
                #7  0x00007f5aff12432c __clone3 (libc.so.6 + 0x10532c)
                
                Stack trace of thread 4294:
                #0  0x00007f5aff0a107c __GI___lll_lock_wait (libc.so.6 + 0x8207c)
                #1  0x00007f5aff0a6750 __pthread_mutex_cond_lock (libc.so.6 + 0x87750)
                #2  0x00007f5aff0a3421 pthread_cond_wait (libc.so.6 + 0x84421)
                #3  0x0000558787b43639 _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (firefox + 0x67639)
                #4  0x00007f5af64638a5 _ZN7mozilla14TaskController13RunPoolThreadEv (libxul.so + 0x20638a5)
                #5  0x00007f5af64636d1 _ZN7mozilla20ThreadFuncPoolThreadEPv (libxul.so + 0x20636d1)
                #6  0x00007f5aff014605 _pt_root (libnspr4.so + 0x45605)
                #7  0x00007f5aff0a40b6 start_thread (libc.so.6 + 0x850b6)
                #8  0x00007f5aff12432c __clone3 (libc.so.6 + 0x10532c)
                
                Stack trace of thread 4288:
                #0  0x00007f5aff0a0e56 __futex_abstimed_wait_common (libc.so.6 + 0x81e56)
                #1  0x00007f5aff0a380c pthread_cond_timedwait (libc.so.6 + 0x8480c)
                #2  0x00007f5aff00abe7 PR_WaitCondVar (libnspr4.so + 0x3bbe7)
                #3  0x00007f5af6a6ce22 _ZL12WatchdogMainPv (libxul.so + 0x266ce22)
                #4  0x00007f5aff014605 _pt_root (libnspr4.so + 0x45605)
                #5  0x00007f5aff0a40b6 start_thread (libc.so.6 + 0x850b6)
                #6  0x00007f5aff12432c __clone3 (libc.so.6 + 0x10532c)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 12.1-2 (OpenMandriva Lx release 4.90)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-openmandriva-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
/etc/gdbinit:9: Error in sourced command file:
Scripting in the "Python" language is not supported in this copy of GDB.
Reading symbols from /usr/lib64/firefox-104.0.1/firefox...
Reading symbols from .gnu_debugdata for /usr/lib64/firefox-104.0.1/firefox...
(No debugging symbols found in .gnu_debugdata for /usr/lib64/firefox-104.0.1/firefox)

warning: Can't open file /memfd:mozilla-ipc (deleted) during file-backed mapping note processing
[New LWP 4281]
[New LWP 4285]
[New LWP 4295]
[New LWP 4294]
[New LWP 4288]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/lib64/firefox-104.0.1/firefox -contentproc -childID 4 -isForBrowser -prefs'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5af676bf83 in mozilla::net::HttpChannelChild::AsyncCallImpl(void (mozilla::net::HttpChannelChild::*)(), nsRunnableMethod<mozilla::net::HttpChannelChild, void, true, (mozilla::RunnableKind)0>**) () from /usr/lib64/firefox-104.0.1/libxul.so
[Current thread is 1 (Thread 0x7f5aff432780 (LWP 4281))]
(gdb) bt full
#0  0x00007f5af676bf83 in mozilla::net::HttpChannelChild::AsyncCallImpl(void (mozilla::net::HttpChannelChild::*)(), nsRunnableMethod<mozilla::net::HttpChannelChild, void, true, (mozilla::RunnableKind)0>**) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#1  0x00007f5af678baad in non-virtual thunk to mozilla::net::HttpChannelChild::AsyncCall(void (mozilla::net::HttpChannelChild::*)(), nsRunnableMethod<mozilla::net::HttpChannelChild, void, true, (mozilla::RunnableKind)0>**) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#2  0x00007f5af676377e in mozilla::net::HttpAsyncAborter<mozilla::net::HttpChannelChild>::AsyncAbort(nsresult) ()
   from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#3  0x00007f5af675f6e7 in mozilla::net::HttpChannelChild::Cancel(nsresult) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#4  0x00007f5af676714a in non-virtual thunk to mozilla::net::HttpChannelChild::Cancel(nsresult) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#5  0x00007f5af65a1c98 in mozilla::net::nsLoadGroup::Cancel(nsresult) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#6  0x00007f5af6b23f02 in nsDocLoader::Stop() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#7  0x00007f5af6b22dd5 in nsDocLoader::Destroy() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#8  0x00007f5af6b22bd9 in nsDocLoader::~nsDocLoader() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#9  0x00007f5af9c7a7a7 in nsDocShell::~nsDocShell() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#10 0x00007f5af9c7abcb in nsDocShell::~nsDocShell() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#11 0x00007f5af6b2366a in nsDocLoader::DeleteCycleCollectable() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#12 0x00007f5af65f732a in mozilla::net::nsUDPMessage::cycleCollection::DeleteCycleCollectable(void*) ()
   from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#13 0x00007f5af63db95a in SnowWhiteKiller::~SnowWhiteKiller() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#14 0x00007f5af63db1f8 in nsCycleCollector::FreeSnowWhite(bool) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#15 0x00007f5af63de8ab in nsCycleCollector::BeginCollection(mozilla::CCReason, ccIsManual, nsICycleCollectorListener*) ()
   from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#16 0x00007f5af63de3f8 in nsCycleCollector::Collect(mozilla::CCReason, ccIsManual, js::SliceBudget&, nsICycleCollectorListener*, bool) ()
   from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#17 0x00007f5af63de1db in nsCycleCollector::ShutdownCollect() () from /usr/lib64/firefox-104.0.1/libxul.so
--Type <RET> for more, q to quit, c to continue without paging--
No symbol table info available.
#18 0x00007f5af63dfd63 in nsCycleCollector_shutdown(bool) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#19 0x00007f5af649bd9c in mozilla::ShutdownXPCOM(nsIServiceManager*) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#20 0x00007f5af649bad6 in NS_ShutdownXPCOM () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#21 0x00007f5afa10bcdf in XRE_TermEmbedding() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#22 0x00007f5af69bba30 in mozilla::ipc::ScopedXREEmbed::Stop() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#23 0x00007f5af88cb62d in mozilla::dom::ContentProcess::CleanUp() () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#24 0x00007f5afa10c389 in XRE_InitChildProcess(int, char**, XREChildData const*) () from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#25 0x00007f5afa11259e in mozilla::BootstrapImpl::XRE_InitChildProcess(int, char**, XREChildData const*) ()
   from /usr/lib64/firefox-104.0.1/libxul.so
No symbol table info available.
#26 0x0000558787afb2d2 in main ()
No symbol table info available.
(gdb) 

```

**Comment by benbullard79** [comment]
We are past FF 104 so this is invalid now.
