### ISSUE TITLE
cpupower-gui fails to start. 

### ISSUE THREAD

**Issue by itchka** [OpenMandrivaAssociation/distribution#2865]
**OpenMandriva version**: znver1 Rome/rolling updated 

**Describe the bug**:
Unable to run cpupower-gui

**Steps to reproduce**:
Run cpupower-gui from terminal (konsole)

**Observed behavior**:
cpupower-gui
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 33, in <module>
    from cpupower_gui.helper import (
  File "/usr/share/cpupower-gui/cpupower_gui/helper.py", line 14, in <module>
    SESSION = BUS.get_object(
              ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: Could not activate remote peer: activation request failed: unknown unit.

**Expected behavior**:
A gui is displayed

**Additional comment**:
**_**All the program dependencies seemed to be installed though the systemd service was not enabled.**_

**I** tried to enable and start the systemd service related to this application
This resulted in the following error**

systemctl start cpupower-gui
Job for cpupower-gui.service failed because the control process exited with error code.
See "systemctl status cpupower-gui.service" and "journalctl -xeu cpupower-gui.service" for details.

Here is the journal content for this failure:

Dec 21 10:44:26 itchka64 cpupower-gui[4275]:   File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 182, >
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:     self.start_service_by_name(bus_name)
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:   File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 277, >
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PAT>
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^>
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:   File "/usr/lib64/python3.11/site-packages/dbus/connection.py", lin>
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:     reply_message = self.send_message_with_reply_and_block(
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 21 10:44:26 itchka64 cpupower-gui[4275]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnk>
Dec 21 10:44:26 itchka64 systemd[1]: cpupower-gui.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://openmandriva.org
░░ 
░░ An ExecStart= process belonging to unit cpupower-gui.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Dec 21 10:44:26 itchka64 systemd[1]: cpupower-gui.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://openmandriva.org
░░ 
░░ The unit cpupower-gui.service has entered the 'failed' state with result 'exit-code'.
Dec 21 10:44:26 itchka64 systemd[1]: Failed to start cpupower-gui.service - Apply cpupower-gui config at boot.
░░ Subject: A start job for unit cpupower-gui.service has failed
░░ Defined-By: systemd
░░ Support: https://openmandriva.org
░░ 
░░ A start job for unit cpupower-gui.service has finished with a failure.
░░ 
░░ The job identifier is 3251 and the job result is failed.
...skipping...
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:   File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 182, >
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:     self.start_service_by_name(bus_name)
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:   File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 277, >
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:     return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PAT>
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^>
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:   File "/usr/lib64/python3.11/site-packages/dbus/connection.py", lin>
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:     reply_message = self.send_message_with_reply_and_block(
Dec 21 10:44:26 itchka64 cpupower-gui[4275]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 21 10:44:26 itchka64 cpupower-gui[4275]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnk>
Dec 21 10:44:26 itchka64 systemd[1]: cpupower-gui.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://openmandriva.org
░░ 
░░ An ExecStart= process belonging to unit cpupower-gui.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Dec 21 10:44:26 itchka64 systemd[1]: cpupower-gui.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://openmandriva.org
░░ 
░░ The unit cpupower-gui.service has entered the 'failed' state with result 'exit-code'.
Dec 21 10:44:26 itchka64 systemd[1]: Failed to start cpupower-gui.service - Apply cpupower-gui config at boot.
░░ Subject: A start job for unit cpupower-gui.service has failed
░░ Defined-By: systemd
░░ Support: https://openmandriva.org
░░ 
░░ A start job for unit cpupower-gui.service has finished with a failure.
░░ 
░░ The job identifier is 3251 and the job result is failed.

**_Further checks at cpupower-gui github issues revealed that an additional service was required named cpupower-gui-helper 
This service was enabled and run without error._**

**_The program was then run again and the following output was obtained._**

$ cpupower-gui
Traceback (most recent call last):
  File "/usr/bin/cpupower-gui", line 367, in <module>
    from cpupower_gui import main
  File "/usr/share/cpupower-gui/cpupower_gui/main.py", line 38, in <module>
    from .window import CpupowerGuiWindow
  File "/usr/share/cpupower-gui/cpupower_gui/window.py", line 23, in <module>
    gi.require_version("Handy", "1")
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available

**_It seems there may be a missing dependency_**

Running dnf install lib64handy-gir1 installed 3 packages.

Running cpupower-gui resulted in a gui.

**_ACTIONS REQUIRED TO FIX THIS BUG:
1: Add libhandy to the package requires
2: Ensure that both cpupower-gui and cpupower-gui-helper are enabled in the systemd configuration if this program is installed_**

**Logs and screenshots if relevant**

**Comment by itchka** [comment]
Fixed 
Added runtime requires and fixed build bug
