### ISSUE TITLE
Deluge-GTK crashes upon clicking to launch it

### ISSUE THREAD

**Issue by CummingCowGirl** [OpenMandrivaAssociation/distribution#2871]
**openmandriva.rome-23.01-plasma.znver1**:
**Deluge 2.11**:

I installed Deluge using Dnf Drake and when it's icon is clicked to launch it it never launches. Trying to launch it through Konsole I get the below.

```
[locutus@Unimatrix-Zero ~]$ deluge
Gtk-Message: 06:10:38.864: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/usr/bin/deluge", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.1.1', 'gui_scripts', 'deluge')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/ui/ui_entry.py", line 140, in start_ui
    ui.start()
  File "/usr/lib/python3.11/site-packages/deluge/ui/gtk3/__init__.py", line 45, in start
    from .gtkui import GtkUI
  File "/usr/lib/python3.11/site-packages/deluge/ui/gtk3/gtkui.py", line 24, in <module>
    from twisted.internet import defer, gtk3reactor
  File "/usr/lib/python3.11/site-packages/twisted/internet/gtk3reactor.py", line 22, in <module>
    from twisted.internet import gireactor
  File "/usr/lib/python3.11/site-packages/twisted/internet/gireactor.py", line 24, in <module>
    import gi.pygtkcompat  # type: ignore[import]
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/gi/pygtkcompat.py", line 9, in <module>
    from pygtkcompat import (enable,
ModuleNotFoundError: No module named 'pygtkcompat
```

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/deluge-gtk-crashes-upon-clicking-to-launch-it/4774/1

**Comment by benbullard79** [comment]
Confirmed in ROME x86_64.

**Comment by mandian** [comment]
deluge-2.1.1-4 should fixed this.
