### ISSUE TITLE
Calibre crashes on startup

### ISSUE THREAD

**Issue by christann404** [OpenMandrivaAssociation/distribution#2940]
Calibre crashes on startup with messages;
calibre
Failed to import PyQt module: PyQt6.QtOpenGLWidgets with error: /usr/lib64/python3.11/site-packages/PyQt6/QtOpenGL.abi3.so: undefined symbol: _ZN20QOpenGLFunctions_ES2C1Ev, version Qt_6
Traceback (most recent call last):
  File "/usr/bin/calibre", line 21, in <module>
    sys.exit(calibre())
             ^^^^^^^^^
  File "/usr/lib64/calibre/calibre/gui_launch.py", line 72, in calibre
    main(args)
  File "/usr/lib64/calibre/calibre/gui2/main.py", line 548, in main
    app, opts, args = init_qt(args)
                      ^^^^^^^^^^^^^
  File "/usr/lib64/calibre/calibre/gui2/main.py", line 122, in init_qt
    app = Application(args, override_program_name=override, windows_app_uid=MAIN_APP_UID)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/calibre/calibre/gui2/__init__.py", line 1110, in __init__
    setup_to_run_webengine()
  File "/usr/lib64/calibre/calibre/gui2/__init__.py", line 1089, in setup_to_run_webengine
    from qt.core import QOpenGLWidget
ImportError: cannot import name 'QOpenGLWidget' from 'qt.core' (/usr/lib64/calibre/qt/core.py)

I guess that it needs to be rebuilt.
[omdv-bug-report-20231012111050.log](https://github.com/OpenMandrivaAssociation/distribution/files/12884110/omdv-bug-report-20231012111050.log)

**Comment by AngryPenguinPL** [comment]
I rebuilt the package in cooker. Can you check if it works now?

**Comment by christann404** [comment]
Thanks, but same problem.This package accesses QT6 through Python. I wonder if it is related to that.

**Comment by christann404** [comment]
The update to Python-Qt6 fixed the problem Calibre now works properly. 

This bug report can be closed.
